  
  [[main]]
  name = "About"
  weight = 100
  identifier = "about"
  url = "/about/"
  
  [[main]]
  name = "Posts"
  identifier = "home"
  weight = 200
  url = "/"

  [[main]]
  name = "Projects"
  weight = 300
  identifier = "portfolio"
  url = "/portfolio/"


  [[main]]
  name = "Accomplishments"
  weight =400
  identifier = "accomplishments"

  [[main]]
  name = "Awards"
  weight = 410
  identifier = "awards"
  url = "/awards/"
  parent = "accomplishments"  

  [[main]]
  name = "Certifications"
  weight = 420
  identifier = "certifications"
  url = "/certifications/"
  parent = "accomplishments"

 [[main]]
  name = "Archive"
  weight = 500
  identifier = "posts"
  url = "/post/"

  [[main]]
  name = "Contact"
  weight = 600
  identifier = "contact"
  url = "/contact/"

  #[[main]]
  #name = "Archiv"
  #url = "/archives/"

  #[[footer]]
  #name = "imprint"
  #weight = 1
  #identifier = "imprint"
  #url = "/imprint/"